name: Update badges

on:
  schedule:
    # Runs at 0am UTC every day
    - cron: "30 17 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: MiguelBorges1/badge-readme@main
        with:
          REPOSITORY: MiguelBorges1/MiguelBorges1
          CREDLY_USER: miguel-borges_credly
          CREDLY_SORT: RECENT
