name: Update badges

on:
  schedule:
    # Runs at 17:30 UTC every day
    - cron: "30 17 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
